from app.core.query_processor import get_preferred_sections


INTENT_SECTION_KEYWORDS = {"symptoms": ["symptom","symptoms","sign","signs","warning sign",]
                           ,"causes": ["cause","causes","risk factor","risk factors","why",]
                           ,"diagnosis": ["diagnosis","diagnose","diagnosed","diagnostic","exam","exams","test","tests","testing",]
                           ,"treatment": ["treatment","treat","therapy","management","managing","home care","self care","self-care",
                            "patient instructions","when to contact","when to call","what to do",]
                            ,"prevention": ["prevention","prevent","preventing","reduce risk","avoiding",],
                            }


# Intent / section matching

def calculate_intent_score(section,intent,preferred_sections):

    if not section or intent == "general":
        return 0.0

    section = section.lower().strip()

    # 1. Exact preferred-section match

    if section in preferred_sections:
        return 1.0

    # 2. Preferred phrase appears in section
    #
    # Example:
    # preferred = "symptoms"
    # section   = "what are the symptoms of diabetes?"

    for preferred in preferred_sections:

        if preferred in section:
            return 1.0

    # 3. Intent-specific keyword matching
    # Handles:
    # "Preventing Migraine Headaches"
    # "How is diabetes diagnosed?"

    keywords = INTENT_SECTION_KEYWORDS.get(intent,[])

    for keyword in keywords:

        if keyword in section:
            return 1.0


    return 0.0

# Final ranking

def final_rank(results,intent,top_k=15):

    if not results:
        return []

    # Preferred sections from query_processor.py

    preferred_sections = [
        section.lower().strip()
        for section in get_preferred_sections(intent)
    ]


    ranked_results = []


    for result in results:

        meta = result.get("metadata",{})


        section = meta.get("section","").lower().strip()

        # 1. CrossEncoder relevance

        rerank_score = float(result.get("rerank_score",0.0))

        # 2. Context relevance
    
        context_score = float(result.get("context_score",rerank_score))

        # 3. Applicability

        applicability_score = float(result.get("applicability_score",context_score))

        # 4. Topic support
        #
        # Generated by applicability_ranker.py

        topic_support_score = float(result.get("topic_support_score",0.5))


        # Keep scores in a safe range.
        #
        # This assumes topic_support_score is intended
        # to represent a 0 -> 1 support score.

        topic_support_score = max(0.0,min(1.0,topic_support_score))

        # 5. Intent / section alignment

        intent_score = calculate_intent_score(section=section,intent=intent,preferred_sections=preferred_sections)

        # 6. Hard rejection
        #
        # Reject candidates that have:
        #
        # - no topic support
        # - very weak applicability
        #
        # This prevents unrelated medical documents from
        # surviving only because they mention the symptom.

        if (topic_support_score <= 0.0and applicability_score < 0.15):
            continue

        # 7. Base semantic relevance
        #
        # Applicability gets the largest weight because
        # we care whether this passage actually answers
        # THIS user's query.

        base_score = (
            0.30 * rerank_score
            + 0.25 * context_score
            + 0.45 * applicability_score
        )


        # 8. Topic support modifier

        if topic_support_score >= 0.75:

            topic_multiplier = 1.15

        elif topic_support_score >= 0.40:

            topic_multiplier = 1.05

        elif topic_support_score > 0.0:

            topic_multiplier = 0.90

        else:

            topic_multiplier = 0.70

        # 9. Intent modifier
        #
        # Intent is only a bonus.
        #
        # It should NEVER make irrelevant content relevant.

        if intent_score >= 1.0:

            intent_multiplier = 1.08

        else:

            intent_multiplier = 1.0

        # 10. Final score

        final_score = (base_score* topic_multiplier* intent_multiplier)


        # 11. Store debugging information

        result["intent_score"] = intent_score

        result["topic_score"] = rerank_score

        result["topic_support_score"] = (
            topic_support_score
        )

        result["base_score"] = (
            base_score
        )

        result["final_score"] = (
            final_score
        )


        ranked_results.append(
            result
        )


    # 12. Sort strongest -> weakest

    ranked_results.sort(
        key=lambda x: x["final_score"],
        reverse=True
    )


    # 13. Return top candidates

    return ranked_results[:top_k]