import {useState} from 'react';
import {HeartPulse,ShieldCheck,Sparkles,RotateCcw} from 'lucide-react';
import LanguageSelector from './components/LanguageSelector';
import LocationButton from './components/LocationButton';
import QueryForm from './components/QueryForm';
import DoctorResults from './components/DoctorResults';
import {submitMedicalQuery} from './services/medicalApi';
const ui={en:{title:'Find the right specialist',subtitle:"Describe your health concern and we'll help identify the appropriate medical specialty and nearby specialists.",privacy:'Your location is only sent with your medical query.',error:'Something went wrong. Please try again.',reset:'New search'},hi:{title:'सही विशेषज्ञ खोजें',subtitle:'अपनी स्वास्थ्य समस्या बताएं और हम उपयुक्त चिकित्सा विशेषज्ञता तथा आपके पास उपलब्ध विशेषज्ञों की पहचान करने में मदद करेंगे।',privacy:'आपका स्थान केवल आपकी चिकित्सा क्वेरी के साथ भेजा जाता है।',error:'कुछ गलत हो गया। कृपया फिर से प्रयास करें।',reset:'नई खोज'},as:{title:'সঠিক বিশেষজ্ঞ বিচাৰি উলিয়াওক',subtitle:'আপোনাৰ স্বাস্থ্যজনিত সমস্যাৰ বিষয়ে কওক আৰু আমি উপযুক্ত চিকিৎসা বিশেষজ্ঞতা আৰু ওচৰৰ বিশেষজ্ঞ বিচাৰি উলিয়াবলৈ সহায় কৰিম।',privacy:'আপোনাৰ অৱস্থান কেৱল আপোনাৰ চিকিৎসা প্ৰশ্নৰ সৈতে পঠিওৱা হয়।',error:'কিবা এটা ভুল হৈছে। অনুগ্ৰহ কৰি পুনৰ চেষ্টা কৰক।',reset:'নতুন অনুসন্ধান'}};
export default function App(){const[language,setLanguage]=useState('en');const[query,setQuery]=useState('');const[location,setLocation]=useState(null);const[locationLoading,setLocationLoading]=useState(false);const[locationError,setLocationError]=useState('');const[loading,setLoading]=useState(false);const[result,setResult]=useState(null);const[error,setError]=useState('');const text=ui[language];
function getLocation(){setLocationError('');if(!navigator.geolocation){setLocationError('Geolocation is not supported by this browser.');return}setLocationLoading(true);navigator.geolocation.getCurrentPosition(p=>{setLocation({latitude:p.coords.latitude,longitude:p.coords.longitude});setLocationLoading(false)},e=>{setLocationLoading(false);setLocationError(e.code===1?'Location permission was denied. Please allow location access and try again.':e.code===2?'Your location could not be determined. Please try again.':'Location detection timed out. Please try again.')},{enableHighAccuracy:true,timeout:15000,maximumAge:300000})}
async function submit(e){e.preventDefault();setError('');if(!query.trim()){setError('Please enter your health concern.');return}if(!location){setError('Please allow your current location before searching.');return}setLoading(true);try{setResult(await submitMedicalQuery({query:query.trim(),latitude:location.latitude,longitude:location.longitude,language}))}catch(err){setError(err.message||text.error)}finally{setLoading(false)}}
function reset(){setQuery('');setResult(null);setError('')}
return <div className="app-shell"><header className="topbar"><div className="brand"><div className="brand-mark"><HeartPulse size={23}/></div><div><strong>MediAssist</strong><span>AI Medical Assistant</span></div></div><div className="header-actions"><div className="secure-label"><ShieldCheck size={16}/>Secure</div><LanguageSelector value={language} onChange={v=>{setLanguage(v);setError('')}}/></div></header><main className="main-content">{!result?<section className="hero"><div className="hero-badge"><Sparkles size={16}/>Intelligent specialist discovery</div><h1>{text.title}</h1><p className="hero-subtitle">{text.subtitle}</p><div className="search-card"><LocationButton location={location} loading={locationLoading} error={locationError} onGetLocation={getLocation}/><div className="divider"/><QueryForm query={query} onQueryChange={setQuery} onSubmit={submit} loading={loading} disabled={!location}/>{error&&<div className="api-error">{error}</div>}</div><div className="privacy-note"><ShieldCheck size={17}/><span>{text.privacy}</span></div></section>:<div className="results-page"><div className="results-topbar"><div><p className="eyebrow">Your search</p><h1>Specialist results</h1></div><button className="secondary-button" onClick={reset}><RotateCcw size={17}/>{text.reset}</button></div><div className="submitted-query"><span>Your query</span><p>{result.query||query}</p></div><DoctorResults result={result}/>{error&&<div className="api-error">{error}</div>}</div>}</main><footer className="footer"><span>AI Medical Assistant</span><span>For informational purposes only. Seek professional medical care when needed.</span></footer></div>}
